version: '3.9'
services:
  sample-mysql:
    image: mysql
    container_name: bean_db
    environment:
      - MYSQL_DATABASE=bean_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=Password1
    ports:
      - "3306:3306"