version: '3.9'
services:
  sample-mysql:
    image: mysql
    container_name: hotel_db
    environment:
      - MYSQL_DATABASE=hotel_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"